<a href="https://colab.research.google.com/github/95ImadEL/Tensorflow-basics/blob/main/TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [10]:
a = tf.constant(5)
print(a)
b = tf.constant([1, 2, 3])
print(b)
C = tf.constant([[2, 1],[3, 4]])
print(C)
D = tf.constant([[[2, 1, 3], [3, 1, 2], [3, 1, 2]],[[4, 3, 2], [5, 3, 4], [3, 1, 2]]])
print(D)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[2 1]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[2 1 3]
  [3 1 2]
  [3 1 2]]

 [[4 3 2]
  [5 3 4]
  [3 1 2]]], shape=(2, 3, 3), dtype=int32)


In [11]:
print(tf.rank(a))
print(tf.rank(b))
print(tf.rank(C))
print(tf.rank(D))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [12]:
print(tf.shape(a))
print(tf.shape(b))
print(tf.shape(C))
print(tf.shape(D))

tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor([2 3 3], shape=(3,), dtype=int32)


In [13]:
print(tf.size(a))
print(tf.size(b))
print(tf.size(C))
print(tf.size(D))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)


In [28]:
tf.random.set_seed(42)

T1 = tf.random.uniform(shape=(5,300))
T2 = tf.random.uniform(shape=(5,300))

T1, T1.shape, T2, T2.shape

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 TensorShape([5, 300]),
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.828

In [29]:
result_multi = T1 @ tf.transpose(T2)
result_multi.shape

TensorShape([5, 5])

In [31]:
result_dot = tf.tensordot(T1,tf.transpose(T2),1)
result_dot.shape

TensorShape([5, 5])

In [32]:
T3 = tf.random.uniform(shape=(224,224,3))

In [35]:
print(tf.math.reduce_min(T3))

tf.Tensor(2.3841858e-07, shape=(), dtype=float32)


In [36]:
print(tf.math.reduce_max(T3))

tf.Tensor(0.9999918, shape=(), dtype=float32)


In [38]:
T4 = tf.random.uniform(shape=(1,224,224,3))
T5 = tf.squeeze(T4)
print(T5.shape)

(224, 224, 3)


In [40]:
T6 = tf.constant([1, 2, 3, 4, 7, 10, 8, 6, 5, 9])
print(tf.math.argmax(T6))

tf.Tensor(5, shape=(), dtype=int64)


In [43]:
print(tf.one_hot(T6,10))

tf.Tensor(
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]], shape=(10, 10), dtype=float32)
